### ISSUE TITLE
Help with Netflix MSL problem

### ISSUE THREAD

**Issue by nzsjb** [nohajc/netflix-mitm-proxy#4]
This is not directly related to the addon but I wondered if you could shed any light on a problem I have as you appear to know a lot about Netflix's MSL.

I have developed my own media player over a number of years and for the last few months I've been trying to natively play Netflix media. I've used the Kodi source as a guide although all of my code is in C#.

I can retrieve the manifest for a movie or TV show but no matter what I have tried the licence request fails with 'This title is not available to watch instantly'. I pass the session ID and challenge that I've obtained by starting a session using the Widevine CDM in the licence request.

I have used the addon to compare what Chrome is doing when a Netflix movie is played against what I'm doing and they look pretty much the same but still no luck. Incidentally Chrome seems to do things a little differently to Kodi, at least according to the Kodi source I looked at fairly recently.

Any help would be appreciated but if you are not interested that's fine too.

**Comment by nohajc** [comment]
Hard to give any general advice. I've also come across this error message before but it was the manifest request that was failing due to an invalid combination of playback profiles.

I'd say, make sure you send user authentication correctly to both manifest and license requests (including cookies).
Otherwise I'd need more information to troubleshoot this.

Is your media player open source by any chance?

**Comment by nzsjb** [comment]
Thanks for the suggestion. I realise my question was a long shot but I’ve been stuck on this for a while now. I’ll check out what I do with the user authentication.

 

My media player is own use only. I’ve developed it over a long period and it pretty comprehensive now covering most forms of media. It would be a nightmare though for me to try and support it for other users. For example, it has its own parsers for many different stream formats and I can only imagine the problems that would throw up in general use. There are one or two areas that might give me some legal problems as well.

 

I do have one open source project though, EPG Collector on Sourceforge. That had a few thousand users in its prime but its waning somewhat now with the advent of Netflix etc.

 

Again thanks for your help. I’ll let you know how I get on.

**Comment by nzsjb** [comment]
I thought you might be interested in this log (attached) from the addon which shows Chrome manifest and licence requests. I’ve annotated it to make it easier to read.

 

The manifest request includes ‘userauthdata’ with the scheme set to NETFLIXID. The licence request doesn’t use ‘userauthdata’ but it includes the service and user tokens from the manifest response.

 

Another thing I don’t understand is that both manifest and licence requests include ‘keyrequestdata’. I thought that was only used for the initial key handshake. Neither manifest nor licence request get the ‘keyresponsedata’ in their respective responses either.

**Comment by nohajc** [comment]
I can't see any attachment but I think I know what you're talking about. There are several ways to do user authentication and I don't understand all the details of it either. Probably the easiest to use is the EMAIL_PASSWORD scheme (instead of NETFLIXID).

It would probably be more helpful if you shared a log of your application's communication instead. Maybe I can tell what's wrong when I see it.

**Comment by nzsjb** [comment]
Thats odd. I can see the file is attached in my sent items in Outlook. Maybe Github loses it if you reply directly.

Anyway here it is again
[proxy.log](https://github.com/nohajc/netflix-mitm-proxy/files/3947643/proxy.log)

And here is the log from my software. It's pretty verbose but if you start from the line that contains the text 'Playing video 80994011 natively' it's got all the MSL interactions. It's using NETFLIXID as the auth data.

[Streaming Support.log](https://github.com/nohajc/netflix-mitm-proxy/files/3947665/Streaming.Support.log)

Appreciate your help on this.

**Comment by nzsjb** [comment]
Tried with EMAIL_PASSWORD. Same result.

**Comment by nohajc** [comment]
Well, looking at the error code `DeviceEolFinal`, isn't it possible you're using an old CDM dll?
Chrome CDM comes with a private key and a certificate which can expire or get revoked.

I'm just guessing here. Not like the error codes are documented anywhere. If you already have the module up-to-date, I honestly don't know what's wrong.

**Comment by nzsjb** [comment]
You are correct. I took the session ID and Challenge from the proxy log created from a Chrome session by your addon  and I successfully retrieved a licence.

I am currently using an old CDM because I couldn't get my CDM wrapper to reliably work with the latest CDM I could find. Random memory exceptions in the CDM. I then read somewhere that the Kodi InputStreamAdaptive was seeing the same issues. I'll look for another version of the CDM.

**Comment by nohajc** [comment]
You can actually retrieve a version list and the libraries directly from google servers:

```
https://dl.google.com/widevine-cdm/versions.txt

https://dl.google.com/widevine-cdm/${WIDEVINE_VERSION}-win-x64.zip
https://dl.google.com/widevine-cdm/${WIDEVINE_VERSION}-win-ia32.zip
```
e.g.
```
https://dl.google.com/widevine-cdm/4.10.1440.18-win-x64.zip
https://dl.google.com/widevine-cdm/4.10.1440.18-win-ia32.zip
```

**Comment by nzsjb** [comment]
You must be a mind reader. I was going to ask you about that as I knew Kodi did an automatic update.

I've tried the newest CDM version -1 (ie 4.10.1582.1) and I got a licence back so maybe I accidently fixed something in my CDM wrapper along the way.

I have had all the parsing code for fragmented MP4 streams working for a long time for unencrypted data so once I implement the decryption code I should be in business.

Thanks again for your assistance. I'm not sure I would ever have gone back to look at the CDM.

Are you familiar with Widevine implementations generally? My local TV provider uses it for their on-demand content and once I have Netflix completed I'm going to look at playing their content natively rather than thru a browser. The don't use MSL though.

**Comment by nohajc** [comment]
Yeah, MSL is Netflix specific and it's the only protocol I've ever really looked at, so you're on your own there. I wouldn't expect anything that complex though. Most providers don't bother with additional layers of encryption.

Anyway, I'm glad I could help. I'm closing the issue now.
