### ISSUE TITLE
Asking about this script

### ISSUE THREAD

**Issue by Thegreydz** [nohajc/netflix-mitm-proxy#9]
Hello bro, I'm sorry for bothering you but i need to understand something, is this script used to decrypt the Netflix msl-v1 content and response data?

If yes then i want to understand something, i followed your tutorial on Netflix ( on my iPhone ) and i indeed can see the requests urls but i can't access to data nor headers and even the log files is empty, so what's exactly going on

**Comment by nohajc** [comment]
Hi, I never tested on iOS but I suspect it has the same problem as Android. The payload is encoded in a different way on mobile devices, so the script will most likely work on PCs only (maybe also web browser on Mac). Currently I don't plan to extend the functionality.
